// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnocytN_pfdbuuKzQQtR1QCv-IRtzc8BE',
    appId: '1:64202454703:web:d7ac3f6bdbc08467d7c65a',
    messagingSenderId: '64202454703',
    projectId: 'app-ten-firebase',
    authDomain: 'app-ten-firebase.firebaseapp.com',
    storageBucket: 'app-ten-firebase.appspot.com',
    measurementId: 'G-TDXDC7ESVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4rKwYnBzeTSmtdCsNq4pERSbHx6d5lBI',
    appId: '1:64202454703:android:ea03b59006c9844dd7c65a',
    messagingSenderId: '64202454703',
    projectId: 'app-ten-firebase',
    storageBucket: 'app-ten-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA80riHFzUhOyiAqYWtvCAeSi25BrG74YE',
    appId: '1:64202454703:ios:97cffb2eaaba3fa6d7c65a',
    messagingSenderId: '64202454703',
    projectId: 'app-ten-firebase',
    storageBucket: 'app-ten-firebase.appspot.com',
    iosClientId: '64202454703-srnhs00jp64oset33g4umapsuabql6ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA80riHFzUhOyiAqYWtvCAeSi25BrG74YE',
    appId: '1:64202454703:ios:97cffb2eaaba3fa6d7c65a',
    messagingSenderId: '64202454703',
    projectId: 'app-ten-firebase',
    storageBucket: 'app-ten-firebase.appspot.com',
    iosClientId: '64202454703-srnhs00jp64oset33g4umapsuabql6ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
